/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logique.Categorie;
import Logique.Chambre;
import Logique.Etages;
import Logique.Generalites;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nahimana
 */
public class UI_Chambres extends javax.swing.JFrame {

    /**
     * Creates new form UI_Chqmbres
     */
    public UI_Chambres() {
        initComponents();
        
        adapter_Chambres();
    }

  void adapter_Chambres(){
  
      Generalites.Centrer_Fenetres(this);
    charger_Etages_ComboBox();
    
    charger_Categories_ComboBox();
      
  }  
  
  void charger_Categories_ComboBox(){
   
     ResultSet result=db.db_Con.extraireData("select * from categorie");
     
     ui_ch_categ.addItem(new Categorie());
     Categorie et=null;
     
     if(result!=null)
         try {
             while(result.next())
              {
                et=new Categorie(result.getString("nom"),result.getFloat("prix"));
                et.setCatID(result.getInt("catID"));
                
                 ui_ch_categ.addItem(et);
             
             }
                 } catch (SQLException ex) {
                     
         Logger.getLogger(UI_Chambres.class.getName()).log(Level.SEVERE, null, ex);
     }}  
  
  
   void charger_Etages_ComboBox(){
   
     ResultSet result=db.db_Con.extraireData("select * from etages");
     ui_ch_et.addItem(new Etages());
     Etages et=null;
     
     if(result!=null)
         try {
             while(result.next())
              {
                et=new Etages();
                
                et.setNumeroEtage(result.getInt("numero_etage"));
                et.setEtID(result.getInt("etID"));
                 ui_ch_et.addItem(et);
             
             }
                 } catch (SQLException ex) {
         Logger.getLogger(UI_Chambres.class.getName()).log(Level.SEVERE, null, ex);
     }}  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ui_ch_et = new javax.swing.JComboBox<>();
        ui_ch_categ = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Numero des Etages");

        jLabel3.setText("Categorie des Chambres");

        ui_ch_et.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ui_ch_etItemStateChanged(evt);
            }
        });

        jButton1.setText("créer une Chambre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ui_ch_categ, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ui_ch_et, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ui_ch_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ui_ch_categ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setText("Creation d'une chambre dans une Etage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ui_ch_etItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ui_ch_etItemStateChanged
        // TODO add your handling code here:
        
        Etages et=(Etages)evt.getItem();        
        num_ch=et.getNumeroEtage()+""+(et.nb_Chambre_Deja_Etage()+1);
        
    }//GEN-LAST:event_ui_ch_etItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Categorie cat=(Categorie)ui_ch_categ.getSelectedItem();
        Etages et=(Etages)ui_ch_et.getSelectedItem();
        
        if(cat.getCatID()==0)
        {  
             Generalites.Donner_info_User("Choisissez s'il vous plait la categorie");
            return;
        }
        
        if(et.getEtID()==0)
        {
         Generalites.Donner_info_User("Choisissez s'il vous plait le numero de l'etage");
            return;
        }
        
        
        Chambre ch=new Chambre();
        
           ch.setCatID(cat);
           ch.setEtID(et);
           ch.setNumero_ch(UI_Chambres.num_ch);
           
           if(ch.creerChambre()>0){
           
            Generalites.Donner_info_User("Felicitation, la chambre vient d'etre cree");
           }
           else Generalites.Donner_info_User("Desole, la chambre n'a pas ete cree");
           
           
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    static String num_ch="";  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Chambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Chambres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Logique.Categorie> ui_ch_categ;
    private javax.swing.JComboBox<Logique.Etages> ui_ch_et;
    // End of variables declaration//GEN-END:variables
}
